### ISSUE TITLE
when I run this doccker-compose keycloak pointing to https://divoc.xiv.in/auth

### ISSUE THREAD

**Issue by tkantheti** [egovernments/DIVOC#332]
Hello All ,  

I am working with Alabama university for covid vaccine solution , I thought this is a suitable solution, When i compose using docker-compose and up and running  

my http://x.xx.xx.xx/portal pointing to https://divoc.xiv.in/auth. 

/portal/public/keycloak,json 
{
  "realm": "divoc",
  "auth-server-url": "https://divoc.xiv.in/auth/",
  "ssl-required": "external",
  "resource": "facility-admin-portal",
  "public-client": true,
  "verify-token-audience": true,
  "use-resource-role-mappings": true,
  "confidential-port": 0
}

modify to my server keycloak , 

Thanks,
TK

**Comment by dileepbapat** [comment]
it is fixed in orchestration branch, will merge to main soon.

**Comment by dileepbapat** [comment]
Thanks for reporting it, fixed in main branch also.

**Comment by tkantheti** [comment]
Hello Dileep ,

I do have few questions regarding running this application. If you have
time please let me know we can have con call quickly. I able login into
your keycloak server and unable to create oTP , run local  environment.

Thanks,
Trilok.
703-585-3565

**Comment by tkantheti** [comment]
Lets me know do you have slack channel, i will join ,

**Comment by dileepbapat** [comment]
👋 Let’s move this to Slack! It’s a faster, simpler way to talk business, share files and work together. You can sign up here: https://join.slack.com/t/newworkspace-oxe4290/shared_invite/zt-mqs8msqq-653mANdHJIraAG0iINPHXg
