### ISSUE TITLE
[DOC] I have name and age incorrect, and no one is is able to modify that.please suggest how name and age can be modified

### ISSUE THREAD

**Issue by deepz1205** [egovernments/DIVOC#541]
I have my name and age incorrect in the certificate.Noone is able to correct through portal

Solution can be to link aadhar card details for name and age so that manual entry errors can be eliminated

**Comment by deepz1205** [comment]
Thanks for the information.I need to travel to Europe and may need the
certificate with correct name and age.
Is there any other way I can get the details rectified presently.I
sincerely request your help in this regard.

**Comment by animarawat** [comment]
Currently there is no other way. The implementation for correction process is under development. We appreciate your patience and request you to check back after a few days.

**Comment by deepz1205** [comment]
Any expected target date for this feature implementation please

**Comment by deepz1205** [comment]
Now that other countries are changing rules for entry with vaccination as one of the key criteria, a certificate with incorrect details is a major concern. When is this update going to rollout, plz suggest.

**Comment by deepz1205** [comment]
My year of birth is entered as **1961** which is wrong.My correct year of birth is **1981.**
My name is entered as Attaluri Naga Venkata **Krishns** Deepak which is wrong.
Correct names is Attaluri Naga Venkata **Krishna** Deepak

When can I get the details corrected,Please consider.i have seen a pull request merged(Fixes #546) to main regarding the age correction.Will it address this issue.

**Comment by bharatkashyap** [comment]
Hey @deepz1205 - I am no authority on the project but the I wrote the PR you've mentioned. That only fixes a bug where the age is incorrect in the certificate *even when* the year is entered correctly.

**Comment by deepz1205** [comment]
Understood, can you please generalize the scope and help others too for the
updation of Age in case of incorrect manual entry.

**Comment by deepz1205** [comment]
@pramodkvarma ...do you have any update on the correction in certificates feature..plz help if you can

**Comment by pramodkvarma** [comment]
I do not have an update from Co-WIN perspective. I suppose DIVOC software fixes needed for correction is done.

@bharatkashyap @dileepbapat can you confirm if DIVOC software fixes needed for cert correction are in place. Of course for India's cert correction Co-WIN team needs to implement the correction policy. This is not the place for Co-WIN discussions. Just asking if DIVOC code changes for cert correction are in place. Thanks.

**Comment by deepz1205** [comment]
@pramodkvarma @bharatkashyap @dileepbapat   Thanks for the reply and for your efforts.It would be great help if someone updates if the correction feature can expected in near furture, as there are so many on twitter too expecting this feature rollout due to the simple reason that the certificate has already became entry criteria for some of the European countries

**Comment by deepz1205** [comment]
@pramodkvarma @bharatkashyap @dileepbapat  Please help me, I neither have the passport number on the certificate and it shows wrong age and a minor spelling mistake in name, when will the update feature be rolled out or any other method to correct the details...really sorry for bugging you on this but I am helpless

**Comment by deepz1205** [comment]
Thanks a lot for rolling out the correction feature
