### ISSUE TITLE
[BUG]Age is reflecting incorrect 

### ISSUE THREAD

**Issue by CodeSideLocal** [egovernments/DIVOC#546]
The age on the certificate is showing incorrect. It is showing as current_age + 1 in the certificate. Though i have entered the correct birth year. Please correct it.

**Comment by animarawat** [comment]
The implementation for correction process is under development. We appreciate your patience and request you to check back after a few days.

**Comment by vibhorebhatnagar** [comment]
I think the calcAge() function only looks at the year of birth  to calculate age. It does not factor in the date, which is why the bug is happening. 

File : backend/vaccination_api/pkg/utils.go

**Comment by bharatkashyap** [comment]
> I think the calcAge() function only looks at the year of birth to calculate age. It does not factor in the date
> File : backend/vaccination_api/pkg/utils.go

Tested the `calcAge` function in this file, which works as expected. The issue is in [this](https://github.com/egovernments/DIVOC/blob/e667697b47a50a552b8d0a8c89a950180217b945/backend/certificate_signer/signer.js#L98) function, where the Javascript-based age calculation fallback function fails to take the months into account.

**Comment by vibhorebhatnagar** [comment]
> > I think the calcAge() function only looks at the year of birth to calculate age. It does not factor in the date
> > File : backend/vaccination_api/pkg/utils.go
> 
> Tested the `calcAge` function in this file, which works as expected. The issue is in [this](https://github.com/egovernments/DIVOC/blob/e667697b47a50a552b8d0a8c89a950180217b945/backend/certificate_signer/signer.js#L98) function, where the Javascript-based age calculation fallback function fails to take the months into account. Have opened a Pull Request to fix this.

Are we sure it does not require a fix in both places? I found a function that uses calcAge() [here](https://github.com/egovernments/DIVOC/blob/f3c524ff0e8e9a2f09193a37758a67e9b7198c31/backend/vaccination_api/pkg/certify_handler.go)  and has very similar logic as the JS function : 

`recipientAge := certifyData.RecipientAge
	if recipientAge == "" {
		recipientAge = calcAge(strfmt.Date(dob))
		log.Info("calculated Age : ", recipientAge)
	}

	recipient := &models.CertificationRequestRecipient{
		Name: &certifyData.RecipientName,
		Age:  recipientAge,
		Address: &models.CertificationRequestRecipientAddress{
			AddressLine1: &certifyData.RecipientAddressLine1,
			AddressLine2: certifyData.RecipientAddressLine2,
			District:     &certifyData.RecipientDistrict,
			Pincode:      &certifyData.RecipientPincode,
			State:        &certifyData.RecipientState,
		},
		Contact:     contact,
		Dob:         dateAdr(strfmt.Date(dob)),
		Gender:      &certifyData.RecipientGender,
		Nationality: &certifyData.RecipientNationality,
		Identity:    &certifyData.RecipientIdentity,
	}`

**Comment by praveenrajput** [comment]
https://github.com/egovernments/DIVOC/issues/546#issuecomment-840326003 I'm getting the wrong age. As my birthday is less than a month away. The certificate is already showing increased age.
