### ISSUE TITLE
[BUG] Security Issue in Identity Access management

### ISSUE THREAD

**Issue by DebashishSaha** [egovernments/DIVOC#592]
Please check the email sent out 16:16 PM 15-05-2021 at egov-systems@egovernments.org this email. I could not report this here due to sensitivity  of the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tejash-jl** [comment]
@DebashishSaha  you have tested the above issue on the demo instance, we are using it as a playground for others to know how the system work.

**Comment by DebashishSaha** [comment]
@tejash-jl , Good to hear that . But why do developers need to access to that portal even if its demo one .

**Comment by DebashishSaha** [comment]
Why do you even changed the password now if its a demo one . I could see all prod urls there . do you mind take it offline through emails ?

**Comment by tejash-jl** [comment]
The password was not changed. Hope your doubts are cleared. Thanks for reaching out. Let us know if you find any other vulnerabilities.
