### ISSUE TITLE
how to download covid vaccination certificate with only beneficiary_reference_id

### ISSUE THREAD

**Issue by ravis81** [egovernments/DIVOC#607]

**Comment by di1** [comment]
Why do you need such feature, if that is allowed any one can download your certificate. OTP login is required

**Comment by ravis81** [comment]
Beacuse the mobile number which is attached with this beneficiary ref id is
wrongly entered by data entry operator at vaccination centre. Now how can i
download certificate of my father i have only bene ref id which is inform
to me from vaccination center

**Comment by ravis81** [comment]
if mobile number is wrongly enter during registration or vaccination then only vaccination center provide the certificate

**Comment by Balaji928** [comment]
I have downloaded my I st dose certificate but my friend accidentally removed my individual member I'd from my cowin account
