### ISSUE TITLE
Wrong age in vaccination certificate [BUG]

### ISSUE THREAD

**Issue by Pravin1120** [egovernments/DIVOC#608]
I vaccinated on spot registeration in vaccination centre. the vaccinator wrongly registered my date of birth and i getting certificate but age is different .how to correct this problems? this is looking like fake certificate and may be problem  travel time. how to correct this??

**Comment by Gagan696** [comment]
Thts the normal thing in our indian govt hospitals. They putt wrong entry and aftr tht patients have to suffer for their mistake. Same thing happen wid me and wid my parents
