### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by banerji1** [egovernments/DIVOC#686]
2nd dose certificate is not generated. I took 2nd dose on 22june,2021. But my 2dose certificate is not generated yet. Only I can see 1dose certificate when I am done with both the shots.
# Please do not enter any personal information, for COWIN / registration / certificate related issues login to https://www.cowin.gov.in/home and report issue
A clear and concise description of what the bug is (only DIVOC api / module).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dileepbapat** [comment]
Please check with COWIN support: https://www.cowin.gov.in/#howcanweHelp
