### ISSUE TITLE
Not getting sms or certificate

### ISSUE THREAD

**Issue by RavinderSingh22** [egovernments/DIVOC#694]
I have taken 1st dose of vaccine on 18 June at vpo Shahpini tehsil-sangaria district hanumangarh Rajasthan 335063. I didn't get any sms or certificate. Mob 8890977161

**Comment by wonderkamakama** [comment]
Same. I have taken the 1st dose of covishield on 26 June 2021 at BKC COVID-19 VACCINATION CENTER 7900012840/900456284 (Mumbai), still I did not receive any sms or the certificate. Mobile Number: 9892517224

**Comment by 8197358365** [comment]
Same problem

**Comment by dileepbapat** [comment]
Please check with COWIN support: https://www.cowin.gov.in/#howcanweHelp
