### ISSUE TITLE
I didn't get my certificate and sms[BUG]

### ISSUE THREAD

**Issue by Sakthivelssll** [egovernments/DIVOC#712]
**Describe the bug**
# Please do not enter any personal information, for COWIN / registration / certificate related issues login to https://www.cowin.gov.in/home and report issue
A clear and concise description of what the bug is (only DIVOC api / module).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by karansolanki5201** [comment]
Try this way but not come any sms in my phone how can i do?

**Comment by gurjitkaursaini** [comment]
I didn't receive my vaccine certificate till now it's already 90 days ....I m not able to take my 2 dose ...pls help me to solve this

**Comment by dileepbapat** [comment]
Please check with COWIN support: https://www.cowin.gov.in/#howcanweHelp
