### ISSUE TITLE
INtigration of COWIN with punjab COVA app

### ISSUE THREAD

**Issue by Harwinder0111** [egovernments/DIVOC#722]
Many people are facing issue in punjab who have got first dose of vaccination through COVA app and moved to other state for work and now their first dose vaccination status in not showing in COWIN app. They cant get second dose of vaccination inmother states'

**Comment by Ravleen19** [comment]
Any update on this??

**Comment by dileepbapat** [comment]
Please check with cowin support https://www.cowin.gov.in/#howcanweHelp
