### ISSUE TITLE
[BUG] WRONG NUMBER REGISTERED IN VACCINATION CENTER WITH MY PHOTO ID ON CO-WIN . I CANT DOWNLOAD MY CERTIFICATE 

### ISSUE THREAD

**Issue by Bappagos** [egovernments/DIVOC#738]
In vaccination center thay put wrong number on my photo id when they register..  And after vaccination i did not receive any massage.. I cant download my certificate in CoWIN app

**Comment by dileepbapat** [comment]
Please check with COWIN support https://www.cowin.gov.in/#howcanweHelp
